added DSDL for proximity sensors
dronecan/DSDL pull request #15
Opened 2022-09-26 12:42 UTC by rishabsingh3003

This adds DSDL to support proximity messages over DroneCAN

2022-10-05 08:22 UTC, peterbarker requested changes

2022-10-19 07:53 UTC, tridge requested changes

2022-10-19 07:53 UTC, tridge commented on ardupilot/equipment/proximity_sensor/21911.Proximity.uavcan
> +
add uint5 flags, with a FLAGS_NONE = 0

2022-10-19 07:53 UTC, tridge commented on ardupilot/equipment/proximity_sensor/21911.Proximity.uavcan
> +uavcan.Timestamp timestamp
think about if you really need the timestamp

2022-11-02 07:21 UTC, tridge approved these changes

2022-11-02 07:22 UTC, merged