Add RPM message: 1045.RPM.uavcan
dronecan/DSDL pull request #53
Opened 2024-03-13 04:38 UTC by IamPete1

Adds a RPM message for things like heli headspeed.

We do have RPM in a couple of other places:
https://github.com/dronecan/DSDL/blob/eb370f198f17e561706d6eaddb02cb06d9e91cf6/com/hobbywing/esc/20050.StatusMsg1.uavcan#L3

https://github.com/dronecan/DSDL/blob/eb370f198f17e561706d6eaddb02cb06d9e91cf6/uavcan/equipment/esc/1031.RPMCommand.uavcan#L8

https://github.com/dronecan/DSDL/blob/eb370f198f17e561706d6eaddb02cb06d9e91cf6/uavcan/equipment/esc/1034.Status.uavcan#L12

https://github.com/dronecan/DSDL/blob/eb370f198f17e561706d6eaddb02cb06d9e91cf6/uavcan/equipment/ice/reciprocating/1120.Status.uavcan#L110

This does use float 32, which is more bits than any of the other rpms but it is a dedicated message, and it still fits in a single frame.

2024-03-13 07:04 UTC, tridge approved these changes

2024-03-19 00:56 UTC, tridge requested changes

2024-03-19 00:56 UTC, tridge commented on dronecan/sensors/rpm/1045.RPM.uavcan
> +uint8 sensor_id
uint16 flags, with a unhealthy bit

2024-03-24 23:56 UTC, IamPete1 commented on dronecan/sensors/rpm/1045.RPM.uavcan
> +uint8 sensor_id
Done.

2024-04-29 23:07 UTC, tridge approved these changes

2024-04-29 23:07 UTC, merged